-- MySQL Script generated by MySQL Workbench
-- 05/16/18 10:50:06
-- MySQL Workbench Forward Engineering
-- Author : Gildas Houlmann
-- Sumarry : 	Creates the database used by the program Scientific_Calculator.
-- 				The database does not have any relation between tables.

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Scientific_Calculator
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Scientific_Calculator` ;

-- -----------------------------------------------------
-- Schema Scientific_Calculator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Scientific_Calculator` DEFAULT CHARACTER SET utf8 ;
USE `Scientific_Calculator` ;

-- -----------------------------------------------------
-- Table `Scientific_Calculator`.`Constant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scientific_Calculator`.`Constant` ;

CREATE TABLE IF NOT EXISTS `Scientific_Calculator`.`Constant` (
  `idConstant` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `value` DOUBLE NOT NULL,
  PRIMARY KEY (`idConstant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scientific_Calculator`.`ArchivedOperation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scientific_Calculator`.`ArchivedOperation` ;

CREATE TABLE IF NOT EXISTS `Scientific_Calculator`.`ArchivedOperation` (
  `idArchivedOperation` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `operationString` TEXT(2048) NOT NULL,
  PRIMARY KEY (`idArchivedOperation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scientific_Calculator`.`Setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scientific_Calculator`.`Setting` ;

CREATE TABLE IF NOT EXISTS `Scientific_Calculator`.`Setting` (
  `idSetting` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `value` INT NULL,
  `defaultValue` INT NOT NULL,
  `minValue` INT NULL,
  `maxValue` INT NULL,
  PRIMARY KEY (`idSetting`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- ----------------------------------------------------
-- Inserting the Constants in the table
-- ----------------------------------------------------

INSERT INTO constant (`name`, `value`) VALUES('Pi', 3.14159265358979323846264338327950288419716939937510582);
INSERT INTO constant (`name`, `value`) VALUES('AvogadroNumber', 602214179000000000000000);
INSERT INTO constant (`name`, `value`) VALUES('LightSpeed', 299792458);


-- ----------------------------------------------------
-- Inserting the settings in the table
-- ----------------------------------------------------

INSERT INTO setting (`name`, defaultValue, minValue, `maxValue`) VALUES('DecimalsAmount', 5, 1, 12);
INSERT INTO setting (`name`, defaultValue, minValue, `maxValue`) VALUES('HistoryAmount', 100, 0, 9999);
